<%@ page contentType="text/html; charset=UTF-8" language="java" pageEncoding="UTF-8" import="java.sql.*" errorPage="" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Performance Humana</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Sistema de Avaliação Física">
    <link href="<%=request.getContextPath() %>/assets/img/favicon.ico" rel="icon" type="image/x-icon">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Gothic+A1" rel="stylesheet">
    <link href="<%=request.getContextPath() %>/assets/css/theme.css" rel="stylesheet" type="text/css" media="all" />
   
</head>
<body>

  <div class="layout layout-nav-side">
      <jsp:include page="menulateralresponsivo2.jsp"></jsp:include>
      <div class="main-container">

        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-11 col-xl-9">
              <section class="py-4 py-lg-5">
              <input type="text" name="nomeCliente" class="form-control text-center mb-4 mt-0" value="${avaliacao.nomeCliente}" readonly>
              <p class="text-center h4">Anamnese</p>
              
							<form action="ServletAnamnese" method="post">
								<input type="hidden" name="txtCodAvaliacao"
									value="${anamnese.codAvaliacao}">
								<div class="form-row border border-dark border-left-0 border-right-0">
									<div class="form-group col-sm-6">
										<label for="labelAtivFisiAtual">Atividade Fís Atual</label> <input
											type="text" class="form-control" id="txtAtividAtual"
											name="txtAtividAtual"
											value="${anamnese.atividadeFisicaAtual}"  maxlength="40">
									</div>
									<div class="form-group col-sm-6">
										<label for="labelAtivFisPret">Atividade a praticar</label> <input
											type="text" class="form-control" id="txtAtividPret"
											name="txtAtividPret"
											value="${anamnese.atividadeFisicaPretendida}" maxlength="80">
									</div>
									<div class="form-group col-sm-6">
										<label for="labelObjetivo">Objetivo</label> <input type="text"
											class="form-control" id="txtObjetivo" name="txtObjetivo"
											value="${anamnese.objetivo}" maxlength="40">
									</div>
									<div class="form-group col-sm-6">
										<label for="labelDisponibilidade">Disponibilidade</label> <select
											id="txtDisponibilidade" name="txtDisponibilidade"
											class="form-control">
											<option><c:out value="${anamnese.disponibilidade}"></c:out></option>
											<option>1 x Semana</option>
											<option>2 x Semana</option>
											<option>3 x Semana</option>
											<option>4 x Semana</option>
											<option>5 x Semana</option>
											<option>6 x Semana</option>
											<option>7 x Semana</option>
										</select>
									</div>
									<div class="form-group col-sm-6">
										<label for="lblFumante">Fumante</label> <select
											id="txtFumante" name="txtFumante" class="form-control">
											<option><c:out value="${anamnese.fumante}"></c:out></option>
											<option>Sim</option>
											<option>Não</option>
										</select>
									</div>
									<div class="form-group col-sm-6">
										<label>Situação</label> <select class="form-control"
											id="situacao" name="situacao">
											<option><c:out value="${anamnese.situacao}"></c:out></option>
											<option>Ativo</option>
											<option>Sedentário</option>
										</select>
									</div>
									<div class="form-group col-sm-6">
										<label for="labelDorLesao">Dor/Lesão</label>
										<textarea class="form-control" id="txtDorLesao"
											name="txtDorLesao" rows="2" maxlength="100"><c:out
												value="${anamnese.dorLesao}" ></c:out></textarea>
									</div>

									<div class="form-group col-sm-6">
										<label for="labelHistoricoFamiliar">Histórico Médico
											Familiar</label>
										<textarea class="form-control" id="txtHistoricoFamiliar"
											name="txtHistoricoFamiliar" rows="2" maxlength="449"><c:out
												value="${anamnese.historicoMedicoFamiliar}"></c:out></textarea>
									</div>

									<div class="form-group col-sm-6">
										<label for="labelFormControlTextarea1">Histórico
											Médico Pessoal</label>
										<textarea class="form-control" id="txtHistoricoPessoal"
											name="txtHistoricoPessoal" rows="2" maxlength="449"><c:out
												value="${anamnese.historicoMedicoPessoal}"></c:out></textarea>
									</div>
									<div class="form-group col-sm-6">
										<label for="labelFormControlObservacoes">Observações</label>
										<textarea class="form-control" id="txtObservacoes"
											name="txtObservacoes" rows="2" maxlength="599"><c:out
												value="${anamnese.observacoes}"></c:out></textarea>
									</div>

								</div>

								<div
									class="form-row">
									<div class="col-12 mb-2 mt-2">
										<p class="text-center"><strong>Pressão Arterial</strong></p>
									</div>

									<div class="form-group col-sm-6">
										<label for="inputDiastolica">PA Sistólica</label> <select
											id="txtPressaoSistolica" name="txtPressaoSistolica"
											class="form-control">
											<option><c:out value="${anamnese.pressaoSistolica}"></c:out></option>
											<option>80</option>
											<option>81</option>
											<option>82</option>
											<option>83</option>
											<option>84</option>
											<option>85</option>
											<option>86</option>
											<option>87</option>
											<option>88</option>
											<option>89</option>
											<option>90</option>
											<option>91</option>
											<option>92</option>
											<option>93</option>
											<option>94</option>
											<option>95</option>
											<option>96</option>
											<option>97</option>
											<option>98</option>
											<option>99</option>
											<option>100</option>
											<option>101</option>
											<option>102</option>
											<option>103</option>
											<option>104</option>
											<option>105</option>
											<option>106</option>
											<option>107</option>
											<option>108</option>
											<option>109</option>
											<option>110</option>
											<option>111</option>
											<option>112</option>
											<option>113</option>
											<option>114</option>
											<option>115</option>
											<option>116</option>
											<option>117</option>
											<option>118</option>
											<option>119</option>
											<option>120</option>
											<option>121</option>
											<option>122</option>
											<option>123</option>
											<option>124</option>
											<option>125</option>
											<option>126</option>
											<option>127</option>
											<option>128</option>
											<option>129</option>
											<option>130</option>
											<option>131</option>
											<option>132</option>
											<option>133</option>
											<option>134</option>
											<option>135</option>
											<option>136</option>
											<option>137</option>
											<option>138</option>
											<option>139</option>
											<option>140</option>
											<option>141</option>
											<option>142</option>
											<option>143</option>
											<option>144</option>
											<option>145</option>
											<option>146</option>
											<option>147</option>
											<option>148</option>
											<option>149</option>
											<option>150</option>
											<option>151</option>
											<option>152</option>
											<option>153</option>
											<option>154</option>
											<option>155</option>
											<option>156</option>
											<option>157</option>
											<option>158</option>
											<option>159</option>
											<option>160</option>
											<option>161</option>
											<option>162</option>
											<option>163</option>
											<option>164</option>
											<option>165</option>
											<option>166</option>
											<option>167</option>
											<option>168</option>
											<option>169</option>
											<option>170</option>
											<option>171</option>
											<option>172</option>
											<option>173</option>
											<option>174</option>
											<option>175</option>
											<option>176</option>
											<option>177</option>
											<option>178</option>
											<option>179</option>
											<option>180</option>
											<option>181</option>
											<option>182</option>
											<option>183</option>
											<option>184</option>
											<option>185</option>
											<option>186</option>
											<option>187</option>
											<option>188</option>
											<option>189</option>
											<option>190</option>
											<option>191</option>
											<option>192</option>
											<option>193</option>
											<option>194</option>
											<option>195</option>
											<option>196</option>
											<option>197</option>
											<option>198</option>
											<option>199</option>
											<option>200</option>
										</select>
									</div>

									<div class="form-group col-sm-6">
										<label for="inputPressaoDiastolica">PA Diastólica</label> <select
											id="txtPressaoDiastolica" name="txtPressaoDiastolica"
											class="form-control">
											<option><c:out value="${anamnese.pressaoDiastolica}"></c:out></option>
											<option>31</option>
											<option>32</option>
											<option>33</option>
											<option>34</option>
											<option>35</option>
											<option>36</option>
											<option>37</option>
											<option>38</option>
											<option>39</option>
											<option>40</option>
											<option>41</option>
											<option>42</option>
											<option>43</option>
											<option>44</option>
											<option>45</option>
											<option>46</option>
											<option>47</option>
											<option>48</option>
											<option>49</option>
											<option>50</option>
											<option>51</option>
											<option>52</option>
											<option>53</option>
											<option>54</option>
											<option>55</option>
											<option>56</option>
											<option>57</option>
											<option>58</option>
											<option>59</option>
											<option>60</option>
											<option>61</option>
											<option>62</option>
											<option>63</option>
											<option>64</option>
											<option>65</option>
											<option>66</option>
											<option>67</option>
											<option>68</option>
											<option>69</option>
											<option>70</option>
											<option>71</option>
											<option>72</option>
											<option>73</option>
											<option>74</option>
											<option>75</option>
											<option>76</option>
											<option>77</option>
											<option>78</option>
											<option>79</option>
											<option>80</option>
											<option>81</option>
											<option>82</option>
											<option>83</option>
											<option>84</option>
											<option>85</option>
											<option>86</option>
											<option>87</option>
											<option>88</option>
											<option>89</option>
											<option>90</option>
											<option>91</option>
											<option>92</option>
											<option>93</option>
											<option>94</option>
											<option>95</option>
											<option>96</option>
											<option>97</option>
											<option>98</option>
											<option>99</option>
											<option>100</option>
											<option>101</option>
											<option>102</option>
											<option>103</option>
											<option>104</option>
											<option>105</option>
											<option>106</option>
											<option>107</option>
											<option>108</option>
											<option>109</option>
											<option>110</option>
											<option>111</option>
											<option>112</option>
											<option>113</option>
											<option>114</option>
											<option>115</option>
											<option>116</option>
											<option>117</option>
											<option>118</option>
											<option>119</option>
											<option>120</option>
										</select>
									</div>
									<div class="form-group col">
										<label>Classificação PA</label> <select class="form-control"
											id="classPA" name="classPA">
											<option><c:out
													value="${anamnese.classificacaoPressaoArterial}"></c:out></option>
											<option><120 - <80 - Ótima</option>
											<option><130 - <85 - Normal</option>
											<option><130-139/85-89 - Limítrofe</option>
											<option>140-159/90-99 - Hipertensão estágio 1</option>
											<option>160-179/100-109 - Hipertensão estágio 2</option>
											<option>≥ 180 - ≥ 110 - Hipertensão estágio 3</option>
											<option>≥ 140 - <90 - Hipertensão Sistólica Isolada</option>
										</select>
									</div>
								</div>
								
								<div class="form-row form-row border border-dark border-left-0 border-right-0">
								<div class="col-12 mt-2 mb-2">
										<p class="text-center">
											<strong>Oximetria</strong>
										</p>
									</div>
								
									<div class="form-group col-sm-6">
										<label for="labelOximetria">Oximetria</label> <select
											id="ID_select_oximetria" name="txtOximetria"
											class="form-control" onchange="classificaOximetria(this.value)">
											<option><c:out value="${anamnese.oximetria}"></c:out></option>
											<option>50</option>
											<option>51</option>
											<option>52</option>
											<option>53</option>
											<option>54</option>
											<option>55</option>
											<option>56</option>
											<option>57</option>
											<option>58</option>
											<option>59</option>
											<option>60</option>
											<option>61</option>
											<option>62</option>
											<option>63</option>
											<option>64</option>
											<option>65</option>
											<option>66</option>
											<option>67</option>
											<option>68</option>
											<option>69</option>
											<option>70</option>
											<option>71</option>
											<option>72</option>
											<option>73</option>
											<option>74</option>
											<option>75</option>
											<option>76</option>
											<option>77</option>
											<option>78</option>
											<option>79</option>
											<option>80</option>
											<option>81</option>
											<option>82</option>
											<option>83</option>
											<option>84</option>
											<option>85</option>
											<option>86</option>
											<option>87</option>
											<option>88</option>
											<option>89</option>
											<option>90</option>
											<option>91</option>
											<option>92</option>
											<option>93</option>
											<option>94</option>
											<option>95</option>
											<option>96</option>
											<option>97</option>
											<option>98</option>
											<option>99</option>
											<option>100</option>
										</select>
									</div>
									<div class="form-group col-sm-6">
										<label>Classificação Oximetria</label> <input type="text"
											class="form-control" id="resultadoOximetria"
											name="resultadoOximetria"
											value="${anamnese.classificacaoOximetria}" readonly>
									</div>
								</div>


								<div
									class="form-row border border-dark border-left-0 border-right-0"
									id="parametrosbiomedicos">
									<div class="col-12 mt-2 mb-2">
										<p class="text-center">
											<strong>Parâmetros bioquímicos(mg/dl)</strong>
										</p>
									</div>

									<div class="form-group col-sm-6" id="entradaDados">
										<label>Glicemia/jejum</label> <select class="form-control"
											name="txtGlicemia" onChange="classificaGlicemia(this.value)">
											<option><c:out value="${anamnese.glicemia}"></c:out></option>
											<option>35</option>
											<option>36</option>
											<option>37</option>
											<option>38</option>
											<option>39</option>
											<option>40</option>
											<option>41</option>
											<option>42</option>
											<option>43</option>
											<option>44</option>
											<option>45</option>
											<option>46</option>
											<option>47</option>
											<option>48</option>
											<option>49</option>
											<option>50</option>
											<option>51</option>
											<option>52</option>
											<option>53</option>
											<option>54</option>
											<option>55</option>
											<option>56</option>
											<option>57</option>
											<option>58</option>
											<option>59</option>
											<option>60</option>
											<option>61</option>
											<option>62</option>
											<option>63</option>
											<option>64</option>
											<option>65</option>
											<option>66</option>
											<option>67</option>
											<option>68</option>
											<option>69</option>
											<option>70</option>
											<option>71</option>
											<option>72</option>
											<option>73</option>
											<option>74</option>
											<option>75</option>
											<option>76</option>
											<option>77</option>
											<option>78</option>
											<option>79</option>
											<option>80</option>
											<option>81</option>
											<option>82</option>
											<option>83</option>
											<option>84</option>
											<option>85</option>
											<option>86</option>
											<option>87</option>
											<option>88</option>
											<option>89</option>
											<option>90</option>
											<option>91</option>
											<option>92</option>
											<option>93</option>
											<option>94</option>
											<option>95</option>
											<option>96</option>
											<option>97</option>
											<option>98</option>
											<option>99</option>
											<option>100</option>
											<option>101</option>
											<option>102</option>
											<option>103</option>
											<option>104</option>
											<option>105</option>
											<option>106</option>
											<option>107</option>
											<option>108</option>
											<option>109</option>
											<option>110</option>
											<option>111</option>
											<option>112</option>
											<option>113</option>
											<option>114</option>
											<option>115</option>
											<option>116</option>
											<option>117</option>
											<option>118</option>
											<option>119</option>
											<option>120</option>
											<option>121</option>
											<option>122</option>
											<option>123</option>
											<option>124</option>
											<option>125</option>
											<option>126</option>
											<option>127</option>
											<option>128</option>
											<option>129</option>
											<option>130</option>
											<option>131</option>
											<option>132</option>
											<option>133</option>
											<option>134</option>
											<option>135</option>
											<option>136</option>
											<option>137</option>
											<option>138</option>
											<option>139</option>
											<option>140</option>
											<option>141</option>
											<option>142</option>
											<option>143</option>
											<option>144</option>
											<option>145</option>
											<option>146</option>
											<option>147</option>
											<option>148</option>
											<option>149</option>
											<option>150</option>
											<option>151</option>
											<option>152</option>
											<option>153</option>
											<option>154</option>
											<option>155</option>
											<option>156</option>
											<option>157</option>
											<option>158</option>
											<option>159</option>
											<option>160</option>
											<option>161</option>
											<option>162</option>
											<option>163</option>
											<option>164</option>
											<option>165</option>
											<option>166</option>
											<option>167</option>
											<option>168</option>
											<option>169</option>
											<option>170</option>
											<option>171</option>
											<option>172</option>
											<option>173</option>
											<option>174</option>
											<option>175</option>
											<option>176</option>
											<option>177</option>
											<option>178</option>
											<option>179</option>
											<option>180</option>
											<option>181</option>
											<option>182</option>
											<option>183</option>
											<option>184</option>
											<option>185</option>
											<option>186</option>
											<option>187</option>
											<option>188</option>
											<option>189</option>
											<option>190</option>
											<option>191</option>
											<option>192</option>
											<option>193</option>
											<option>194</option>
											<option>195</option>
											<option>196</option>
											<option>197</option>
											<option>198</option>
											<option>199</option>
											<option>200</option>
											<option>201</option>
											<option>202</option>
											<option>203</option>
											<option>204</option>
											<option>205</option>
											<option>206</option>
											<option>207</option>
											<option>208</option>
											<option>209</option>
											<option>210</option>
											<option>211</option>
											<option>212</option>
											<option>213</option>
											<option>214</option>
											<option>215</option>
											<option>216</option>
											<option>217</option>
											<option>218</option>
											<option>219</option>
											<option>220</option>
											<option>221</option>
											<option>222</option>
											<option>223</option>
											<option>224</option>
											<option>225</option>
											<option>226</option>
											<option>227</option>
											<option>228</option>
											<option>229</option>
											<option>230</option>
											<option>231</option>
											<option>232</option>
											<option>233</option>
											<option>234</option>
											<option>235</option>
											<option>236</option>
											<option>237</option>
											<option>238</option>
											<option>239</option>
											<option>240</option>
											<option>241</option>
											<option>242</option>
											<option>243</option>
											<option>244</option>
											<option>245</option>
											<option>246</option>
											<option>247</option>
											<option>248</option>
											<option>249</option>
											<option>250</option>
											<option>251</option>
											<option>252</option>
											<option>253</option>
											<option>254</option>
											<option>255</option>
											<option>256</option>
											<option>257</option>
											<option>258</option>
											<option>259</option>
											<option>260</option>
											<option>261</option>
											<option>262</option>
											<option>263</option>
											<option>264</option>
											<option>265</option>
											<option>266</option>
											<option>267</option>
											<option>268</option>
											<option>269</option>
											<option>270</option>
											<option>271</option>
											<option>272</option>
											<option>273</option>
											<option>274</option>
											<option>275</option>
											<option>276</option>
											<option>277</option>
											<option>278</option>
											<option>279</option>
											<option>280</option>
											<option>281</option>
											<option>282</option>
											<option>283</option>
											<option>284</option>
											<option>285</option>
											<option>286</option>
											<option>287</option>
											<option>288</option>
											<option>289</option>
											<option>290</option>
											<option>291</option>
											<option>292</option>
											<option>293</option>
											<option>294</option>
											<option>295</option>
											<option>296</option>
											<option>297</option>
											<option>298</option>
											<option>299</option>
											<option>300</option>
											<option>301</option>
											<option>302</option>
											<option>303</option>
											<option>304</option>
											<option>305</option>
											<option>306</option>
											<option>307</option>
											<option>308</option>
											<option>309</option>
											<option>310</option>
											<option>311</option>
											<option>312</option>
											<option>313</option>
											<option>314</option>
											<option>315</option>
											<option>316</option>
											<option>317</option>
											<option>318</option>
											<option>319</option>
											<option>320</option>
											<option>321</option>
											<option>322</option>
											<option>323</option>
											<option>324</option>
											<option>325</option>
											<option>326</option>
											<option>327</option>
											<option>328</option>
											<option>329</option>
											<option>330</option>
											<option>331</option>
											<option>332</option>
											<option>333</option>
											<option>334</option>
											<option>335</option>
											<option>336</option>
											<option>337</option>
											<option>338</option>
											<option>339</option>
											<option>340</option>
											<option>341</option>
											<option>342</option>
											<option>343</option>
											<option>344</option>
											<option>345</option>
											<option>346</option>
											<option>347</option>
											<option>348</option>
											<option>349</option>
											<option>350</option>
											<option>351</option>
											<option>352</option>
											<option>353</option>
											<option>354</option>
											<option>355</option>
											<option>356</option>
											<option>357</option>
											<option>358</option>
											<option>359</option>
											<option>360</option>
											<option>361</option>
											<option>362</option>
											<option>363</option>
											<option>364</option>
											<option>365</option>
											<option>366</option>
											<option>367</option>
											<option>368</option>
											<option>369</option>
											<option>370</option>
											<option>371</option>
											<option>372</option>
											<option>373</option>
											<option>374</option>
											<option>375</option>
											<option>376</option>
											<option>377</option>
											<option>378</option>
											<option>379</option>
											<option>380</option>
											<option>381</option>
											<option>382</option>
											<option>383</option>
											<option>384</option>
											<option>385</option>
											<option>386</option>
											<option>387</option>
											<option>388</option>
											<option>389</option>
											<option>390</option>
											<option>391</option>
											<option>392</option>
											<option>393</option>
											<option>394</option>
											<option>395</option>
											<option>396</option>
											<option>397</option>
											<option>398</option>
											<option>399</option>
											<option>400</option>
										</select>
									</div>
									<div class="form-group col-sm-6">
										<label>Resultado</label> <input type="text"
											class="form-control" id="resultadoGlicemia"
											name="resultadoGlicemia" value="${anamnese.resultaGlicemia}"
											readonly>
									</div>

									<div class="form-group col-sm-6" id="entradaDados">
										<label>Triglicerídio</label> <select class="form-control"
											name="txtTriglicerideo" id="txtTriglicerideo"
											onChange="classificacaoTriglicerideo(this.value)">
											<option><c:out value="${anamnese.triglicerideo}"></c:out></option>
											<option>40</option>
											<option>41</option>
											<option>42</option>
											<option>43</option>
											<option>44</option>
											<option>45</option>
											<option>46</option>
											<option>47</option>
											<option>48</option>
											<option>49</option>
											<option>50</option>
											<option>51</option>
											<option>52</option>
											<option>53</option>
											<option>54</option>
											<option>55</option>
											<option>56</option>
											<option>57</option>
											<option>58</option>
											<option>59</option>
											<option>60</option>
											<option>61</option>
											<option>62</option>
											<option>63</option>
											<option>64</option>
											<option>65</option>
											<option>66</option>
											<option>67</option>
											<option>68</option>
											<option>69</option>
											<option>70</option>
											<option>71</option>
											<option>72</option>
											<option>73</option>
											<option>74</option>
											<option>75</option>
											<option>76</option>
											<option>77</option>
											<option>78</option>
											<option>79</option>
											<option>80</option>
											<option>81</option>
											<option>82</option>
											<option>83</option>
											<option>84</option>
											<option>85</option>
											<option>86</option>
											<option>87</option>
											<option>88</option>
											<option>89</option>
											<option>90</option>
											<option>91</option>
											<option>92</option>
											<option>93</option>
											<option>94</option>
											<option>95</option>
											<option>96</option>
											<option>97</option>
											<option>98</option>
											<option>99</option>
											<option>100</option>
											<option>101</option>
											<option>102</option>
											<option>103</option>
											<option>104</option>
											<option>105</option>
											<option>106</option>
											<option>107</option>
											<option>108</option>
											<option>109</option>
											<option>110</option>
											<option>111</option>
											<option>112</option>
											<option>113</option>
											<option>114</option>
											<option>115</option>
											<option>116</option>
											<option>117</option>
											<option>118</option>
											<option>119</option>
											<option>120</option>
											<option>121</option>
											<option>122</option>
											<option>123</option>
											<option>124</option>
											<option>125</option>
											<option>126</option>
											<option>127</option>
											<option>128</option>
											<option>129</option>
											<option>130</option>
											<option>131</option>
											<option>132</option>
											<option>133</option>
											<option>134</option>
											<option>135</option>
											<option>136</option>
											<option>137</option>
											<option>138</option>
											<option>139</option>
											<option>140</option>
											<option>141</option>
											<option>142</option>
											<option>143</option>
											<option>144</option>
											<option>145</option>
											<option>146</option>
											<option>147</option>
											<option>148</option>
											<option>149</option>
											<option>150</option>
											<option>151</option>
											<option>152</option>
											<option>153</option>
											<option>154</option>
											<option>155</option>
											<option>156</option>
											<option>157</option>
											<option>158</option>
											<option>159</option>
											<option>160</option>
											<option>161</option>
											<option>162</option>
											<option>163</option>
											<option>164</option>
											<option>165</option>
											<option>166</option>
											<option>167</option>
											<option>168</option>
											<option>169</option>
											<option>170</option>
											<option>171</option>
											<option>172</option>
											<option>173</option>
											<option>174</option>
											<option>175</option>
											<option>176</option>
											<option>177</option>
											<option>178</option>
											<option>179</option>
											<option>180</option>
											<option>181</option>
											<option>182</option>
											<option>183</option>
											<option>184</option>
											<option>185</option>
											<option>186</option>
											<option>187</option>
											<option>188</option>
											<option>189</option>
											<option>190</option>
											<option>191</option>
											<option>192</option>
											<option>193</option>
											<option>194</option>
											<option>195</option>
											<option>196</option>
											<option>197</option>
											<option>198</option>
											<option>199</option>
											<option>200</option>
											<option>201</option>
											<option>202</option>
											<option>203</option>
											<option>204</option>
											<option>205</option>
											<option>206</option>
											<option>207</option>
											<option>208</option>
											<option>209</option>
											<option>210</option>
											<option>211</option>
											<option>212</option>
											<option>213</option>
											<option>214</option>
											<option>215</option>
											<option>216</option>
											<option>217</option>
											<option>218</option>
											<option>219</option>
											<option>220</option>
											<option>221</option>
											<option>222</option>
											<option>223</option>
											<option>224</option>
											<option>225</option>
											<option>226</option>
											<option>227</option>
											<option>228</option>
											<option>229</option>
											<option>230</option>
											<option>231</option>
											<option>232</option>
											<option>233</option>
											<option>234</option>
											<option>235</option>
											<option>236</option>
											<option>237</option>
											<option>238</option>
											<option>239</option>
											<option>240</option>
											<option>241</option>
											<option>242</option>
											<option>243</option>
											<option>244</option>
											<option>245</option>
											<option>246</option>
											<option>247</option>
											<option>248</option>
											<option>249</option>
											<option>250</option>
											<option>251</option>
											<option>252</option>
											<option>253</option>
											<option>254</option>
											<option>255</option>
											<option>256</option>
											<option>257</option>
											<option>258</option>
											<option>259</option>
											<option>260</option>
											<option>261</option>
											<option>262</option>
											<option>263</option>
											<option>264</option>
											<option>265</option>
											<option>266</option>
											<option>267</option>
											<option>268</option>
											<option>269</option>
											<option>270</option>
											<option>271</option>
											<option>272</option>
											<option>273</option>
											<option>274</option>
											<option>275</option>
											<option>276</option>
											<option>277</option>
											<option>278</option>
											<option>279</option>
											<option>280</option>
											<option>281</option>
											<option>282</option>
											<option>283</option>
											<option>284</option>
											<option>285</option>
											<option>286</option>
											<option>287</option>
											<option>288</option>
											<option>289</option>
											<option>290</option>
											<option>291</option>
											<option>292</option>
											<option>293</option>
											<option>294</option>
											<option>295</option>
											<option>296</option>
											<option>297</option>
											<option>298</option>
											<option>299</option>
											<option>300</option>
											<option>301</option>
											<option>302</option>
											<option>303</option>
											<option>304</option>
											<option>305</option>
											<option>306</option>
											<option>307</option>
											<option>308</option>
											<option>309</option>
											<option>310</option>
											<option>311</option>
											<option>312</option>
											<option>313</option>
											<option>314</option>
											<option>315</option>
											<option>316</option>
											<option>317</option>
											<option>318</option>
											<option>319</option>
											<option>320</option>
											<option>321</option>
											<option>322</option>
											<option>323</option>
											<option>324</option>
											<option>325</option>
											<option>326</option>
											<option>327</option>
											<option>328</option>
											<option>329</option>
											<option>330</option>
											<option>331</option>
											<option>332</option>
											<option>333</option>
											<option>334</option>
											<option>335</option>
											<option>336</option>
											<option>337</option>
											<option>338</option>
											<option>339</option>
											<option>340</option>
											<option>341</option>
											<option>342</option>
											<option>343</option>
											<option>344</option>
											<option>345</option>
											<option>346</option>
											<option>347</option>
											<option>348</option>
											<option>349</option>
											<option>350</option>
											<option>351</option>
											<option>352</option>
											<option>353</option>
											<option>354</option>
											<option>355</option>
											<option>356</option>
											<option>357</option>
											<option>358</option>
											<option>359</option>
											<option>360</option>
											<option>361</option>
											<option>362</option>
											<option>363</option>
											<option>364</option>
											<option>365</option>
											<option>366</option>
											<option>367</option>
											<option>368</option>
											<option>369</option>
											<option>370</option>
											<option>371</option>
											<option>372</option>
											<option>373</option>
											<option>374</option>
											<option>375</option>
											<option>376</option>
											<option>377</option>
											<option>378</option>
											<option>379</option>
											<option>380</option>
											<option>381</option>
											<option>382</option>
											<option>383</option>
											<option>384</option>
											<option>385</option>
											<option>386</option>
											<option>387</option>
											<option>388</option>
											<option>389</option>
											<option>390</option>
											<option>391</option>
											<option>392</option>
											<option>393</option>
											<option>394</option>
											<option>395</option>
											<option>396</option>
											<option>397</option>
											<option>398</option>
											<option>399</option>
											<option>400</option>
											<option>401</option>
											<option>402</option>
											<option>403</option>
											<option>404</option>
											<option>405</option>
											<option>406</option>
											<option>407</option>
											<option>408</option>
											<option>409</option>
											<option>410</option>
											<option>411</option>
											<option>412</option>
											<option>413</option>
											<option>414</option>
											<option>415</option>
											<option>416</option>
											<option>417</option>
											<option>418</option>
											<option>419</option>
											<option>420</option>
											<option>421</option>
											<option>422</option>
											<option>423</option>
											<option>424</option>
											<option>425</option>
											<option>426</option>
											<option>427</option>
											<option>428</option>
											<option>429</option>
											<option>430</option>
											<option>431</option>
											<option>432</option>
											<option>433</option>
											<option>434</option>
											<option>435</option>
											<option>436</option>
											<option>437</option>
											<option>438</option>
											<option>439</option>
											<option>440</option>
											<option>441</option>
											<option>442</option>
											<option>443</option>
											<option>444</option>
											<option>445</option>
											<option>446</option>
											<option>447</option>
											<option>448</option>
											<option>449</option>
											<option>450</option>
											<option>451</option>
											<option>452</option>
											<option>453</option>
											<option>454</option>
											<option>455</option>
											<option>456</option>
											<option>457</option>
											<option>458</option>
											<option>459</option>
											<option>460</option>
											<option>461</option>
											<option>462</option>
											<option>463</option>
											<option>464</option>
											<option>465</option>
											<option>466</option>
											<option>467</option>
											<option>468</option>
											<option>469</option>
											<option>470</option>
											<option>471</option>
											<option>472</option>
											<option>473</option>
											<option>474</option>
											<option>475</option>
											<option>476</option>
											<option>477</option>
											<option>478</option>
											<option>479</option>
											<option>480</option>
											<option>481</option>
											<option>482</option>
											<option>483</option>
											<option>484</option>
											<option>485</option>
											<option>486</option>
											<option>487</option>
											<option>488</option>
											<option>489</option>
											<option>490</option>
											<option>491</option>
											<option>492</option>
											<option>493</option>
											<option>494</option>
											<option>495</option>
											<option>496</option>
											<option>497</option>
											<option>498</option>
											<option>499</option>
											<option>500</option>
											<option>501</option>
											<option>502</option>
											<option>503</option>
											<option>504</option>
											<option>505</option>
											<option>506</option>
											<option>507</option>
											<option>508</option>
											<option>509</option>
											<option>510</option>
											<option>511</option>
											<option>512</option>
											<option>513</option>
											<option>514</option>
											<option>515</option>
											<option>516</option>
											<option>517</option>
											<option>518</option>
											<option>519</option>
											<option>520</option>
											<option>521</option>
											<option>522</option>
											<option>523</option>
											<option>524</option>
											<option>525</option>
											<option>526</option>
											<option>527</option>
											<option>528</option>
											<option>529</option>
											<option>530</option>
											<option>531</option>
											<option>532</option>
											<option>533</option>
											<option>534</option>
											<option>535</option>
											<option>536</option>
											<option>537</option>
											<option>538</option>
											<option>539</option>
											<option>540</option>
											<option>541</option>
											<option>542</option>
											<option>543</option>
											<option>544</option>
											<option>545</option>
											<option>546</option>
											<option>547</option>
											<option>548</option>
											<option>549</option>
											<option>550</option>
											<option>551</option>
											<option>552</option>
											<option>553</option>
											<option>554</option>
											<option>555</option>
											<option>556</option>
											<option>557</option>
											<option>558</option>
											<option>559</option>
											<option>560</option>
											<option>561</option>
											<option>562</option>
											<option>563</option>
											<option>564</option>
											<option>565</option>
											<option>566</option>
											<option>567</option>
											<option>568</option>
											<option>569</option>
											<option>570</option>
											<option>571</option>
											<option>572</option>
											<option>573</option>
											<option>574</option>
											<option>575</option>
											<option>576</option>
											<option>577</option>
											<option>578</option>
											<option>579</option>
											<option>580</option>
											<option>581</option>
											<option>582</option>
											<option>583</option>
											<option>584</option>
											<option>585</option>
											<option>586</option>
											<option>587</option>
											<option>588</option>
											<option>589</option>
											<option>590</option>
											<option>591</option>
											<option>592</option>
											<option>593</option>
											<option>594</option>
											<option>595</option>
											<option>596</option>
											<option>597</option>
											<option>598</option>
											<option>599</option>
											<option>600</option>
											<option>601</option>
											<option>602</option>
											<option>603</option>
											<option>604</option>
											<option>605</option>
											<option>606</option>
											<option>607</option>
											<option>608</option>
											<option>609</option>
											<option>610</option>
											<option>611</option>
											<option>612</option>
											<option>613</option>
											<option>614</option>
											<option>615</option>
											<option>616</option>
											<option>617</option>
											<option>618</option>
											<option>619</option>
											<option>620</option>
											<option>621</option>
											<option>622</option>
											<option>623</option>
											<option>624</option>
											<option>625</option>
											<option>626</option>
											<option>627</option>
											<option>628</option>
											<option>629</option>
											<option>630</option>
											<option>631</option>
											<option>632</option>
											<option>633</option>
											<option>634</option>
											<option>635</option>
											<option>636</option>
											<option>637</option>
											<option>638</option>
											<option>639</option>
											<option>640</option>
											<option>641</option>
											<option>642</option>
											<option>643</option>
											<option>644</option>
											<option>645</option>
											<option>646</option>
											<option>647</option>
											<option>648</option>
											<option>649</option>
											<option>650</option>
											<option>651</option>
											<option>652</option>
											<option>653</option>
											<option>654</option>
											<option>655</option>
											<option>656</option>
											<option>657</option>
											<option>658</option>
											<option>659</option>
											<option>660</option>
											<option>661</option>
											<option>662</option>
											<option>663</option>
											<option>664</option>
											<option>665</option>
											<option>666</option>
											<option>667</option>
											<option>668</option>
											<option>669</option>
											<option>670</option>
											<option>671</option>
											<option>672</option>
											<option>673</option>
											<option>674</option>
											<option>675</option>
											<option>676</option>
											<option>677</option>
											<option>678</option>
											<option>679</option>
											<option>680</option>
											<option>681</option>
											<option>682</option>
											<option>683</option>
											<option>684</option>
											<option>685</option>
											<option>686</option>
											<option>687</option>
											<option>688</option>
											<option>689</option>
											<option>690</option>
											<option>691</option>
											<option>692</option>
											<option>693</option>
											<option>694</option>
											<option>695</option>
											<option>696</option>
											<option>697</option>
											<option>698</option>
											<option>699</option>
											<option>700</option>
											<option>701</option>
											<option>702</option>
											<option>703</option>
											<option>704</option>
											<option>705</option>
											<option>706</option>
											<option>707</option>
											<option>708</option>
											<option>709</option>
											<option>710</option>
											<option>711</option>
											<option>712</option>
											<option>713</option>
											<option>714</option>
											<option>715</option>
											<option>716</option>
											<option>717</option>
											<option>718</option>
											<option>719</option>
											<option>720</option>
											<option>721</option>
											<option>722</option>
											<option>723</option>
											<option>724</option>
											<option>725</option>
											<option>726</option>
											<option>727</option>
											<option>728</option>
											<option>729</option>
											<option>730</option>
											<option>731</option>
											<option>732</option>
											<option>733</option>
											<option>734</option>
											<option>735</option>
											<option>736</option>
											<option>737</option>
											<option>738</option>
											<option>739</option>
											<option>740</option>
											<option>741</option>
											<option>742</option>
											<option>743</option>
											<option>744</option>
											<option>745</option>
											<option>746</option>
											<option>747</option>
											<option>748</option>
											<option>749</option>
											<option>750</option>
											<option>751</option>
											<option>752</option>
											<option>753</option>
											<option>754</option>
											<option>755</option>
											<option>756</option>
											<option>757</option>
											<option>758</option>
											<option>759</option>
											<option>760</option>
											<option>761</option>
											<option>762</option>
											<option>763</option>
											<option>764</option>
											<option>765</option>
											<option>766</option>
											<option>767</option>
											<option>768</option>
											<option>769</option>
											<option>770</option>
											<option>771</option>
											<option>772</option>
											<option>773</option>
											<option>774</option>
											<option>775</option>
											<option>776</option>
											<option>777</option>
											<option>778</option>
											<option>779</option>
											<option>780</option>
											<option>781</option>
											<option>782</option>
											<option>783</option>
											<option>784</option>
											<option>785</option>
											<option>786</option>
											<option>787</option>
											<option>788</option>
											<option>789</option>
											<option>790</option>
											<option>791</option>
											<option>792</option>
											<option>793</option>
											<option>794</option>
											<option>795</option>
											<option>796</option>
											<option>797</option>
											<option>798</option>
											<option>799</option>
											<option>800</option>
										</select>
									</div>
									<div class="form-group col-sm-6">
										<label>Resultado</label> <input type="text"
											class="form-control" id="resultadoTriglicerideo"
											name="resultadoTriglicerideo"
											value="${anamnese.resulta_triglicerideo}" readonly>
									</div>

									<div class="form-group col-sm-6" id="entradaDados">
										<label>Colesterol Total</label> <select class="form-control"
											onChange="classificaColesterolTotal(this.value)"
											id="txtColesterol" name="txtColesterol">
											<option><c:out value="${anamnese.colesterolTotal}"></c:out></option>
											<option>70</option>
											<option>71</option>
											<option>72</option>
											<option>73</option>
											<option>74</option>
											<option>75</option>
											<option>76</option>
											<option>77</option>
											<option>78</option>
											<option>79</option>
											<option>80</option>
											<option>81</option>
											<option>82</option>
											<option>83</option>
											<option>84</option>
											<option>85</option>
											<option>86</option>
											<option>87</option>
											<option>88</option>
											<option>89</option>
											<option>90</option>
											<option>91</option>
											<option>92</option>
											<option>93</option>
											<option>94</option>
											<option>95</option>
											<option>96</option>
											<option>97</option>
											<option>98</option>
											<option>99</option>
											<option>100</option>
											<option>101</option>
											<option>102</option>
											<option>103</option>
											<option>104</option>
											<option>105</option>
											<option>106</option>
											<option>107</option>
											<option>108</option>
											<option>109</option>
											<option>110</option>
											<option>111</option>
											<option>112</option>
											<option>113</option>
											<option>114</option>
											<option>115</option>
											<option>116</option>
											<option>117</option>
											<option>118</option>
											<option>119</option>
											<option>120</option>
											<option>121</option>
											<option>122</option>
											<option>123</option>
											<option>124</option>
											<option>125</option>
											<option>126</option>
											<option>127</option>
											<option>128</option>
											<option>129</option>
											<option>130</option>
											<option>131</option>
											<option>132</option>
											<option>133</option>
											<option>134</option>
											<option>135</option>
											<option>136</option>
											<option>137</option>
											<option>138</option>
											<option>139</option>
											<option>140</option>
											<option>141</option>
											<option>142</option>
											<option>143</option>
											<option>144</option>
											<option>145</option>
											<option>146</option>
											<option>147</option>
											<option>148</option>
											<option>149</option>
											<option>150</option>
											<option>151</option>
											<option>152</option>
											<option>153</option>
											<option>154</option>
											<option>155</option>
											<option>156</option>
											<option>157</option>
											<option>158</option>
											<option>159</option>
											<option>160</option>
											<option>161</option>
											<option>162</option>
											<option>163</option>
											<option>164</option>
											<option>165</option>
											<option>166</option>
											<option>167</option>
											<option>168</option>
											<option>169</option>
											<option>170</option>
											<option>171</option>
											<option>172</option>
											<option>173</option>
											<option>174</option>
											<option>175</option>
											<option>176</option>
											<option>177</option>
											<option>178</option>
											<option>179</option>
											<option>180</option>
											<option>181</option>
											<option>182</option>
											<option>183</option>
											<option>184</option>
											<option>185</option>
											<option>186</option>
											<option>187</option>
											<option>188</option>
											<option>189</option>
											<option>190</option>
											<option>191</option>
											<option>192</option>
											<option>193</option>
											<option>194</option>
											<option>195</option>
											<option>196</option>
											<option>197</option>
											<option>198</option>
											<option>199</option>
											<option>200</option>
											<option>201</option>
											<option>202</option>
											<option>203</option>
											<option>204</option>
											<option>205</option>
											<option>206</option>
											<option>207</option>
											<option>208</option>
											<option>209</option>
											<option>210</option>
											<option>211</option>
											<option>212</option>
											<option>213</option>
											<option>214</option>
											<option>215</option>
											<option>216</option>
											<option>217</option>
											<option>218</option>
											<option>219</option>
											<option>220</option>
											<option>221</option>
											<option>222</option>
											<option>223</option>
											<option>224</option>
											<option>225</option>
											<option>226</option>
											<option>227</option>
											<option>228</option>
											<option>229</option>
											<option>230</option>
											<option>231</option>
											<option>232</option>
											<option>233</option>
											<option>234</option>
											<option>235</option>
											<option>236</option>
											<option>237</option>
											<option>238</option>
											<option>239</option>
											<option>240</option>
											<option>241</option>
											<option>242</option>
											<option>243</option>
											<option>244</option>
											<option>245</option>
											<option>246</option>
											<option>247</option>
											<option>248</option>
											<option>249</option>
											<option>250</option>
											<option>251</option>
											<option>252</option>
											<option>253</option>
											<option>254</option>
											<option>255</option>
											<option>256</option>
											<option>257</option>
											<option>258</option>
											<option>259</option>
											<option>260</option>
											<option>261</option>
											<option>262</option>
											<option>263</option>
											<option>264</option>
											<option>265</option>
											<option>266</option>
											<option>267</option>
											<option>268</option>
											<option>269</option>
											<option>270</option>
											<option>271</option>
											<option>272</option>
											<option>273</option>
											<option>274</option>
											<option>275</option>
											<option>276</option>
											<option>277</option>
											<option>278</option>
											<option>279</option>
											<option>280</option>
											<option>281</option>
											<option>282</option>
											<option>283</option>
											<option>284</option>
											<option>285</option>
											<option>286</option>
											<option>287</option>
											<option>288</option>
											<option>289</option>
											<option>290</option>
											<option>291</option>
											<option>292</option>
											<option>293</option>
											<option>294</option>
											<option>295</option>
											<option>296</option>
											<option>297</option>
											<option>298</option>
											<option>299</option>
											<option>300</option>
											<option>301</option>
											<option>302</option>
											<option>303</option>
											<option>304</option>
											<option>305</option>
											<option>306</option>
											<option>307</option>
											<option>308</option>
											<option>309</option>
											<option>310</option>
											<option>311</option>
											<option>312</option>
											<option>313</option>
											<option>314</option>
											<option>315</option>
											<option>316</option>
											<option>317</option>
											<option>318</option>
											<option>319</option>
											<option>320</option>
											<option>321</option>
											<option>322</option>
											<option>323</option>
											<option>324</option>
											<option>325</option>
											<option>326</option>
											<option>327</option>
											<option>328</option>
											<option>329</option>
											<option>330</option>
											<option>331</option>
											<option>332</option>
											<option>333</option>
											<option>334</option>
											<option>335</option>
											<option>336</option>
											<option>337</option>
											<option>338</option>
											<option>339</option>
											<option>340</option>
											<option>341</option>
											<option>342</option>
											<option>343</option>
											<option>344</option>
											<option>345</option>
											<option>346</option>
											<option>347</option>
											<option>348</option>
											<option>349</option>
											<option>350</option>
											<option>351</option>
											<option>352</option>
											<option>353</option>
											<option>354</option>
											<option>355</option>
											<option>356</option>
											<option>357</option>
											<option>358</option>
											<option>359</option>
											<option>360</option>
											<option>361</option>
											<option>362</option>
											<option>363</option>
											<option>364</option>
											<option>365</option>
											<option>366</option>
											<option>367</option>
											<option>368</option>
											<option>369</option>
											<option>370</option>
											<option>371</option>
											<option>372</option>
											<option>373</option>
											<option>374</option>
											<option>375</option>
											<option>376</option>
											<option>377</option>
											<option>378</option>
											<option>379</option>
											<option>380</option>
											<option>381</option>
											<option>382</option>
											<option>383</option>
											<option>384</option>
											<option>385</option>
											<option>386</option>
											<option>387</option>
											<option>388</option>
											<option>389</option>
											<option>390</option>
											<option>391</option>
											<option>392</option>
											<option>393</option>
											<option>394</option>
											<option>395</option>
											<option>396</option>
											<option>397</option>
											<option>398</option>
											<option>399</option>
											<option>400</option>
										</select>
									</div>
									<div class="form-group col-sm-6">
										<label>Resultado</label> <input type="text"
											class="form-control" id="resultadoColesterol"
											name="resultadoColesterol"
											value="${anamnese.resulta_colesterol}" readonly>
									</div>

									<div class="form-group col-sm-6" id="entradaDados">
										<label>HDLc(Bom)</label> <select class="form-control"
											id="txtHdl" name="txtHdl"
											onChange="classificaHdl(this.value)">
											<option><c:out value="${anamnese.hdl}"></c:out>
											</option>
											<option>10</option>
											<option>11</option>
											<option>12</option>
											<option>13</option>
											<option>14</option>
											<option>15</option>
											<option>16</option>
											<option>17</option>
											<option>18</option>
											<option>19</option>
											<option>20</option>
											<option>21</option>
											<option>22</option>
											<option>23</option>
											<option>24</option>
											<option>25</option>
											<option>26</option>
											<option>27</option>
											<option>28</option>
											<option>29</option>
											<option>30</option>
											<option>31</option>
											<option>32</option>
											<option>33</option>
											<option>34</option>
											<option>35</option>
											<option>36</option>
											<option>37</option>
											<option>38</option>
											<option>39</option>
											<option>40</option>
											<option>41</option>
											<option>42</option>
											<option>43</option>
											<option>44</option>
											<option>45</option>
											<option>46</option>
											<option>47</option>
											<option>48</option>
											<option>49</option>
											<option>50</option>
											<option>51</option>
											<option>52</option>
											<option>53</option>
											<option>54</option>
											<option>55</option>
											<option>56</option>
											<option>57</option>
											<option>58</option>
											<option>59</option>
											<option>60</option>
											<option>61</option>
											<option>62</option>
											<option>63</option>
											<option>64</option>
											<option>65</option>
											<option>66</option>
											<option>67</option>
											<option>68</option>
											<option>69</option>
											<option>70</option>
											<option>71</option>
											<option>72</option>
											<option>73</option>
											<option>74</option>
											<option>75</option>
											<option>76</option>
											<option>77</option>
											<option>78</option>
											<option>79</option>
											<option>80</option>
											<option>81</option>
											<option>82</option>
											<option>83</option>
											<option>84</option>
											<option>85</option>
											<option>86</option>
											<option>87</option>
											<option>88</option>
											<option>89</option>
											<option>90</option>
											<option>91</option>
											<option>92</option>
											<option>93</option>
											<option>94</option>
											<option>95</option>
											<option>96</option>
											<option>97</option>
											<option>98</option>
											<option>99</option>
											<option>100</option>
										</select>
									</div>
									<div class="form-group col-sm-6">
										<label>Resultado</label> <input type="text"
											class="form-control" id="resultadoHdl" name="resultadoHdl"
											value="${anamnese.resulta_hdl}" readonly>
									</div>

									<div class="form-group col-sm-6" id="entradaDados">
										<label>LDLc(Ruim)</label> <select class="form-control"
											id="txtLdl" name="txtLdl"
											onChange="classificaLdl(this.value)">
											<option><c:out value="${anamnese.ldl}"></c:out></option>
											<option>20</option>
											<option>21</option>
											<option>22</option>
											<option>23</option>
											<option>24</option>
											<option>25</option>
											<option>26</option>
											<option>27</option>
											<option>28</option>
											<option>29</option>
											<option>30</option>
											<option>31</option>
											<option>32</option>
											<option>33</option>
											<option>34</option>
											<option>35</option>
											<option>36</option>
											<option>37</option>
											<option>38</option>
											<option>39</option>
											<option>40</option>
											<option>41</option>
											<option>42</option>
											<option>43</option>
											<option>44</option>
											<option>45</option>
											<option>46</option>
											<option>47</option>
											<option>48</option>
											<option>49</option>
											<option>50</option>
											<option>51</option>
											<option>52</option>
											<option>53</option>
											<option>54</option>
											<option>55</option>
											<option>56</option>
											<option>57</option>
											<option>58</option>
											<option>59</option>
											<option>60</option>
											<option>61</option>
											<option>62</option>
											<option>63</option>
											<option>64</option>
											<option>65</option>
											<option>66</option>
											<option>67</option>
											<option>68</option>
											<option>69</option>
											<option>70</option>
											<option>71</option>
											<option>72</option>
											<option>73</option>
											<option>74</option>
											<option>75</option>
											<option>76</option>
											<option>77</option>
											<option>78</option>
											<option>79</option>
											<option>80</option>
											<option>81</option>
											<option>82</option>
											<option>83</option>
											<option>84</option>
											<option>85</option>
											<option>86</option>
											<option>87</option>
											<option>88</option>
											<option>89</option>
											<option>90</option>
											<option>91</option>
											<option>92</option>
											<option>93</option>
											<option>94</option>
											<option>95</option>
											<option>96</option>
											<option>97</option>
											<option>98</option>
											<option>99</option>
											<option>100</option>
											<option>101</option>
											<option>102</option>
											<option>103</option>
											<option>104</option>
											<option>105</option>
											<option>106</option>
											<option>107</option>
											<option>108</option>
											<option>109</option>
											<option>110</option>
											<option>111</option>
											<option>112</option>
											<option>113</option>
											<option>114</option>
											<option>115</option>
											<option>116</option>
											<option>117</option>
											<option>118</option>
											<option>119</option>
											<option>120</option>
											<option>121</option>
											<option>122</option>
											<option>123</option>
											<option>124</option>
											<option>125</option>
											<option>126</option>
											<option>127</option>
											<option>128</option>
											<option>129</option>
											<option>130</option>
											<option>131</option>
											<option>132</option>
											<option>133</option>
											<option>134</option>
											<option>135</option>
											<option>136</option>
											<option>137</option>
											<option>138</option>
											<option>139</option>
											<option>140</option>
											<option>141</option>
											<option>142</option>
											<option>143</option>
											<option>144</option>
											<option>145</option>
											<option>146</option>
											<option>147</option>
											<option>148</option>
											<option>149</option>
											<option>150</option>
											<option>151</option>
											<option>152</option>
											<option>153</option>
											<option>154</option>
											<option>155</option>
											<option>156</option>
											<option>157</option>
											<option>158</option>
											<option>159</option>
											<option>160</option>
											<option>161</option>
											<option>162</option>
											<option>163</option>
											<option>164</option>
											<option>165</option>
											<option>166</option>
											<option>167</option>
											<option>168</option>
											<option>169</option>
											<option>170</option>
											<option>171</option>
											<option>172</option>
											<option>173</option>
											<option>174</option>
											<option>175</option>
											<option>176</option>
											<option>177</option>
											<option>178</option>
											<option>179</option>
											<option>180</option>
											<option>181</option>
											<option>182</option>
											<option>183</option>
											<option>184</option>
											<option>185</option>
											<option>186</option>
											<option>187</option>
											<option>188</option>
											<option>189</option>
											<option>190</option>
											<option>191</option>
											<option>192</option>
											<option>193</option>
											<option>194</option>
											<option>195</option>
											<option>196</option>
											<option>197</option>
											<option>198</option>
											<option>199</option>
											<option>200</option>
											<option>201</option>
											<option>202</option>
											<option>203</option>
											<option>204</option>
											<option>205</option>
											<option>206</option>
											<option>207</option>
											<option>208</option>
											<option>209</option>
											<option>210</option>
											<option>211</option>
											<option>212</option>
											<option>213</option>
											<option>214</option>
											<option>215</option>
											<option>216</option>
											<option>217</option>
											<option>218</option>
											<option>219</option>
											<option>220</option>
											<option>221</option>
											<option>222</option>
											<option>223</option>
											<option>224</option>
											<option>225</option>
											<option>226</option>
											<option>227</option>
											<option>228</option>
											<option>229</option>
											<option>230</option>
											<option>231</option>
											<option>232</option>
											<option>233</option>
											<option>234</option>
											<option>235</option>
											<option>236</option>
											<option>237</option>
											<option>238</option>
											<option>239</option>
											<option>240</option>
											<option>241</option>
											<option>242</option>
											<option>243</option>
											<option>244</option>
											<option>245</option>
											<option>246</option>
											<option>247</option>
											<option>248</option>
											<option>249</option>
											<option>250</option>
											<option>251</option>
											<option>252</option>
											<option>253</option>
											<option>254</option>
											<option>255</option>
											<option>256</option>
											<option>257</option>
											<option>258</option>
											<option>259</option>
											<option>260</option>
											<option>261</option>
											<option>262</option>
											<option>263</option>
											<option>264</option>
											<option>265</option>
											<option>266</option>
											<option>267</option>
											<option>268</option>
											<option>269</option>
											<option>270</option>
											<option>271</option>
											<option>272</option>
											<option>273</option>
											<option>274</option>
											<option>275</option>
											<option>276</option>
											<option>277</option>
											<option>278</option>
											<option>279</option>
											<option>280</option>
											<option>281</option>
											<option>282</option>
											<option>283</option>
											<option>284</option>
											<option>285</option>
											<option>286</option>
											<option>287</option>
											<option>288</option>
											<option>289</option>
											<option>290</option>
											<option>291</option>
											<option>292</option>
											<option>293</option>
											<option>294</option>
											<option>295</option>
											<option>296</option>
											<option>297</option>
											<option>298</option>
											<option>299</option>
											<option>300</option>
										</select>
									</div>
									<div class="form-group col-sm-6">
										<label>Resultado</label> <input type="text"
											class="form-control" id="resultadoLdl" name="resultadoLdl"
											value="${anamnese.resulta_ldl}" readonly>
									</div>

									<div class="form-group col-sm-6" id="entradaDados">
										<label>VLDLc(Bom)</label> <select class="form-control"
											id="txtVldl" name="txtVldl"
											onChange="classificaVldl(this.value)">
											<option><c:out value="${anamnese.vldl}"></c:out></option>
											<option>10</option>
											<option>11</option>
											<option>12</option>
											<option>13</option>
											<option>14</option>
											<option>15</option>
											<option>16</option>
											<option>17</option>
											<option>18</option>
											<option>19</option>
											<option>20</option>
											<option>21</option>
											<option>22</option>
											<option>23</option>
											<option>24</option>
											<option>25</option>
											<option>26</option>
											<option>27</option>
											<option>28</option>
											<option>29</option>
											<option>30</option>
											<option>31</option>
											<option>32</option>
											<option>33</option>
											<option>34</option>
											<option>35</option>
											<option>36</option>
											<option>37</option>
											<option>38</option>
											<option>39</option>
											<option>40</option>
											<option>41</option>
											<option>42</option>
											<option>43</option>
											<option>44</option>
											<option>45</option>
											<option>46</option>
											<option>47</option>
											<option>48</option>
											<option>49</option>
											<option>50</option>
											<option>51</option>
											<option>52</option>
											<option>53</option>
											<option>54</option>
											<option>55</option>
											<option>56</option>
											<option>57</option>
											<option>58</option>
											<option>59</option>
											<option>60</option>
											<option>61</option>
											<option>62</option>
											<option>63</option>
											<option>64</option>
											<option>65</option>
											<option>66</option>
											<option>67</option>
											<option>68</option>
											<option>69</option>
											<option>70</option>
											<option>71</option>
											<option>72</option>
											<option>73</option>
											<option>74</option>
											<option>75</option>
											<option>76</option>
											<option>77</option>
											<option>78</option>
											<option>79</option>
											<option>80</option>
											<option>81</option>
											<option>82</option>
											<option>83</option>
											<option>84</option>
											<option>85</option>
											<option>86</option>
											<option>87</option>
											<option>88</option>
											<option>89</option>
											<option>90</option>
											<option>91</option>
											<option>92</option>
											<option>93</option>
											<option>94</option>
											<option>95</option>
											<option>96</option>
											<option>97</option>
											<option>98</option>
											<option>99</option>
											<option>100</option>
										</select>
									</div>
									<div class="form-group col-sm-6">
										<label>Resultado</label> <input type="text"
											class="form-control" id="resultadoVldl" name="resultadoVldl"
											value="${anamnese.resulta_vldl}" readonly>
									</div>
								</div>


								<div class="mt-1">
									<button type="submit" class="btn btn-primary col-2">Salvar</button>
								</div>

							</form>
						</section>
            </div>
          </div>
        </div>

      </div>
    </div>
  
  <jsp:include page="javascript.jsp"></jsp:include>
  <script type="text/javascript">
  function classificaOximetria(valor){
		let num = valor;
		if(valor<=89){
			document.getElementById('resultadoOximetria').value = 'Investigar';
		}else if (valor>=90){
			document.getElementById('resultadoOximetria').value = 'Normal';
		}
	}
		
		function classificaGlicemia(glicemia){
			
			let num = glicemia;
			
			if(glicemia<=70){
				document.getElementById('resultadoGlicemia').value = 'Hipoglicemia';
			}else if (glicemia<=100){
				document.getElementById('resultadoGlicemia').value = 'Normal';
			}else if(glicemia<=126){
				document.getElementById('resultadoGlicemia').value = 'Alterada';
			}else if(glicemia>126){
				document.getElementById('resultadoGlicemia').value = 'Diabetes';
			}
	}
		
		function classificacaoTriglicerideo(triglicerideo){
			let num = triglicerideo;
			
			if(triglicerideo<=150){
				document.getElementById('resultadoTriglicerideo').value = 'Desejável';
			}else if(triglicerideo<=199){
				document.getElementById('resultadoTriglicerideo').value = 'Limite alto';
			}else if(triglicerideo<=499){
				document.getElementById('resultadoTriglicerideo').value = 'Alto';
			}else{
				document.getElementById('resultadoTriglicerideo').value = 'Muito alto';
			}
		}
		
		function classificaColesterolTotal(colesterol){
			let num = colesterol;
			if(colesterol<=190){
				document.getElementById('resultadoColesterol').value = 'Desejável';
			}else if(colesterol<=239){
				document.getElementById('resultadoColesterol').value = 'Limitrofe alto';
			}else{
				document.getElementById('resultadoColesterol').value = 'Muito alto';
			}
		}
		classificaHdl(this.value)
		
		function classificaHdl(hdl){
			let num = hdl;
			if(hdl<=40){
				document.getElementById('resultadoHdl').value = 'Baixo';
			}else if(hdl<=59){
				document.getElementById('resultadoHdl').value = 'bom';
			}else{
				document.getElementById('resultadoHdl').value = 'Desejável';
			}
		}
		
		function classificaLdl(ldl){
			let num = ldl;
			if(ldl<=100){
				document.getElementById('resultadoLdl').value = 'Ótimo';
			}else if(ldl<=129){
				document.getElementById('resultadoLdl').value = 'Acima';
			}else if(ldl<=159){
				document.getElementById('resultadoLdl').value = 'Limitrofe alto';
			}else if(ldl<=189){
				document.getElementById('resultadoLdl').value = 'Alto';
			}else{
				document.getElementById('resultadoLdl').value = 'Muito Alto';	
			}
		}
		
		function classificaVldl(vldl){
			let num = vldl;
			if(vldl<=30){
				document.getElementById('resultadoVldl').value = 'Baixo';
			}else if (vldl<40){
				document.getElementById('resultadoVldl').value = 'Ideal';
			}else{
				document.getElementById('resultadoVldl').value = 'Alto';
			}
		}
		
		
  
  </script>
</body>

</html>